// Code generated by MockGen. DO NOT EDIT.
// Source: infra/contract/cache.go
//
// Generated by this command:
//
//	mockgen -package mocks -source=infra/contract/cache.go -destination=infra/mocks/cache.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockLoginAttemptStore is a mock of LoginAttemptStore interface.
type MockLoginAttemptStore struct {
	ctrl     *gomock.Controller
	recorder *MockLoginAttemptStoreMockRecorder
	isgomock struct{}
}

// MockLoginAttemptStoreMockRecorder is the mock recorder for MockLoginAttemptStore.
type MockLoginAttemptStoreMockRecorder struct {
	mock *MockLoginAttemptStore
}

// NewMockLoginAttemptStore creates a new mock instance.
func NewMockLoginAttemptStore(ctrl *gomock.Controller) *MockLoginAttemptStore {
	mock := &MockLoginAttemptStore{ctrl: ctrl}
	mock.recorder = &MockLoginAttemptStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLoginAttemptStore) EXPECT() *MockLoginAttemptStoreMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockLoginAttemptStore) Delete(ctx context.Context, keys ...string) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range keys {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Delete", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockLoginAttemptStoreMockRecorder) Delete(ctx any, keys ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, keys...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockLoginAttemptStore)(nil).Delete), varargs...)
}

// GetInt mocks base method.
func (m *MockLoginAttemptStore) GetInt(ctx context.Context, key string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInt", ctx, key)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetInt indicates an expected call of GetInt.
func (mr *MockLoginAttemptStoreMockRecorder) GetInt(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInt", reflect.TypeOf((*MockLoginAttemptStore)(nil).GetInt), ctx, key)
}

// IncrBy mocks base method.
func (m *MockLoginAttemptStore) IncrBy(ctx context.Context, key string, delta int64, ttl time.Duration) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrBy", ctx, key, delta, ttl)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IncrBy indicates an expected call of IncrBy.
func (mr *MockLoginAttemptStoreMockRecorder) IncrBy(ctx, key, delta, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrBy", reflect.TypeOf((*MockLoginAttemptStore)(nil).IncrBy), ctx, key, delta, ttl)
}
