// Code generated by MockGen. DO NOT EDIT.
// Source: application/contract/cache.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
)

// MockCacheManager is a mock of CacheManager interface.
type MockCacheManager struct {
	ctrl     *gomock.Controller
	recorder *MockCacheManagerMockRecorder
}

// MockCacheManagerMockRecorder is the mock recorder for MockCacheManager.
type MockCacheManagerMockRecorder struct {
	mock *MockCacheManager
}

// NewMockCacheManager creates a new mock instance.
func NewMockCacheManager(ctrl *gomock.Controller) *MockCacheManager {
	mock := &MockCacheManager{ctrl: ctrl}
	mock.recorder = &MockCacheManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCacheManager) EXPECT() *MockCacheManagerMockRecorder {
	return m.recorder
}

// CleanAll mocks base method.
func (m *MockCacheManager) CleanAll() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CleanAll")
	ret0, _ := ret[0].(error)
	return ret0
}

// CleanAll indicates an expected call of CleanAll.
func (mr *MockCacheManagerMockRecorder) CleanAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CleanAll", reflect.TypeOf((*MockCacheManager)(nil).CleanAll))
}

// Delete mocks base method.
func (m *MockCacheManager) Delete(keys ...string) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{}
	for _, a := range keys {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Delete", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockCacheManagerMockRecorder) Delete(keys ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockCacheManager)(nil).Delete), keys...)
}

// GetExpiration mocks base method.
func (m *MockCacheManager) GetExpiration(key string) (time.Duration, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetExpiration", key)
	ret0, _ := ret[0].(time.Duration)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetExpiration indicates an expected call of GetExpiration.
func (mr *MockCacheManagerMockRecorder) GetExpiration(key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetExpiration", reflect.TypeOf((*MockCacheManager)(nil).GetExpiration), key)
}

// GetInt mocks base method.
func (m *MockCacheManager) GetInt(key string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInt", key)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetInt indicates an expected call of GetInt.
func (mr *MockCacheManagerMockRecorder) GetInt(key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInt", reflect.TypeOf((*MockCacheManager)(nil).GetInt), key)
}

// GetItem mocks base method.
func (m *MockCacheManager) GetItem(key string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetItem", key)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetItem indicates an expected call of GetItem.
func (mr *MockCacheManagerMockRecorder) GetItem(key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetItem", reflect.TypeOf((*MockCacheManager)(nil).GetItem), key)
}

// GetString mocks base method.
func (m *MockCacheManager) GetString(key string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetString", key)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetString indicates an expected call of GetString.
func (mr *MockCacheManagerMockRecorder) GetString(key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetString", reflect.TypeOf((*MockCacheManager)(nil).GetString), key)
}

// GetStruct mocks base method.
func (m *MockCacheManager) GetStruct(key string, data interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStruct", key, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// GetStruct indicates an expected call of GetStruct.
func (mr *MockCacheManagerMockRecorder) GetStruct(key, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStruct", reflect.TypeOf((*MockCacheManager)(nil).GetStruct), key, data)
}

// Increase mocks base method.
func (m *MockCacheManager) Increase(key string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Increase", key)
	ret0, _ := ret[0].(error)
	return ret0
}

// Increase indicates an expected call of Increase.
func (mr *MockCacheManagerMockRecorder) Increase(key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Increase", reflect.TypeOf((*MockCacheManager)(nil).Increase), key)
}

// SetExpiration mocks base method.
func (m *MockCacheManager) SetExpiration(key string, expiration time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetExpiration", key, expiration)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetExpiration indicates an expected call of SetExpiration.
func (mr *MockCacheManagerMockRecorder) SetExpiration(key, expiration interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetExpiration", reflect.TypeOf((*MockCacheManager)(nil).SetExpiration), key, expiration)
}

// SetItem mocks base method.
func (m *MockCacheManager) SetItem(key string, data []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetItem", key, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetItem indicates an expected call of SetItem.
func (mr *MockCacheManagerMockRecorder) SetItem(key, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetItem", reflect.TypeOf((*MockCacheManager)(nil).SetItem), key, data)
}

// SetItemWithExpiration mocks base method.
func (m *MockCacheManager) SetItemWithExpiration(key string, data []byte, expiration time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetItemWithExpiration", key, data, expiration)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetItemWithExpiration indicates an expected call of SetItemWithExpiration.
func (mr *MockCacheManagerMockRecorder) SetItemWithExpiration(key, data, expiration interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetItemWithExpiration", reflect.TypeOf((*MockCacheManager)(nil).SetItemWithExpiration), key, data, expiration)
}

// SetString mocks base method.
func (m *MockCacheManager) SetString(key, data string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetString", key, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetString indicates an expected call of SetString.
func (mr *MockCacheManagerMockRecorder) SetString(key, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetString", reflect.TypeOf((*MockCacheManager)(nil).SetString), key, data)
}

// SetStringWithExpiration mocks base method.
func (m *MockCacheManager) SetStringWithExpiration(key, data string, expiration time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetStringWithExpiration", key, data, expiration)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetStringWithExpiration indicates an expected call of SetStringWithExpiration.
func (mr *MockCacheManagerMockRecorder) SetStringWithExpiration(key, data, expiration interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetStringWithExpiration", reflect.TypeOf((*MockCacheManager)(nil).SetStringWithExpiration), key, data, expiration)
}

// SetStruct mocks base method.
func (m *MockCacheManager) SetStruct(key string, data interface{}, expiration time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetStruct", key, data, expiration)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetStruct indicates an expected call of SetStruct.
func (mr *MockCacheManagerMockRecorder) SetStruct(key, data, expiration interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetStruct", reflect.TypeOf((*MockCacheManager)(nil).SetStruct), key, data, expiration)
}

// SetStructWithExpiration mocks base method.
func (m *MockCacheManager) SetStructWithExpiration(key string, data interface{}, expiration time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetStructWithExpiration", key, data, expiration)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetStructWithExpiration indicates an expected call of SetStructWithExpiration.
func (mr *MockCacheManagerMockRecorder) SetStructWithExpiration(key, data, expiration interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetStructWithExpiration", reflect.TypeOf((*MockCacheManager)(nil).SetStructWithExpiration), key, data, expiration)
}
