package main

import (
	"github.com/diegoclair/go_boilerplate/internal/application/service"
	"github.com/diegoclair/go_boilerplate/internal/transport/rest"
)

// the swagger documentation will be generated by https://github.com/diegoclair/goswag
func main() {
	//	@title			Go Boilerplate API
	//	@version		1.0
	//	@description	This is an API documentation for go boilerplate

	//	@contact.name	Email
	//	@contact.email	diego93rodrigues@gmail.com

	//	@host			localhost:5000
	//	@schemes		http
	//	@servers.url	http://localhost:5000

	server := rest.NewRestServer(&service.Apps{}, nil, nil, "")
	server.Router.GenerateSwagger()
}
